apiVersion: v2
name: metric-summarizer
description: AI-powered observability and monitoring solution for OpenShift clusters
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: llm-service
    version: 0.1.0
    repository: https://rh-ai-kickstart.github.io/ai-architecture-charts
  - name: llama-stack
    version: 0.2.9
    repository: https://rh-ai-kickstart.github.io/ai-architecture-charts
  - name: pgvector
    version: 0.1.0
    repository: https://rh-ai-kickstart.github.io/ai-architecture-charts  
