apiVersion: v2
name: rag
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: llm-service
    version: 0.1.0
    repository: https://ganeshmurthy.github.io/ai-architecture-charts/FOLSOM-GAUDI/
  - name: llama-stack
    version: 0.2.9
    repository: https://ganeshmurthy.github.io/ai-architecture-charts/FOLSOM-GAUDI/
  - name: pgvector
    version: 0.1.0
    repository: https://ganeshmurthy.github.io/ai-architecture-charts/FOLSOM-GAUDI/
