apiVersion: v2
name: rag
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: llm-service
    version: 0.1.0
    repository: file://../../../../ai-architecture-charts/llm-service/helm
  - name: llama-stack
    version: 0.2.9
    repository: file://../../../../ai-architecture-charts/llama-stack/helm
  - name: pgvector
    version: 0.1.0
    repository: file://../../../../ai-architecture-charts/pgvector/helm
